staging:
  adapter: postgresql
  database: proejct_mosul_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

staging:
  adapter: postgresql
  database: proejct_mosul_staging
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  adapter: postgresql
  database: project_mosul_development
  username: rails_dev
  password: rails_dev

test:
  adapter: postgresql
  database: project_mosul_test
  username: rails_dev
  password: rails_dev