production:
  adapter: postgresql
  database: project_mosul_production
  host: localhost
  port: 5432
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

staging:
  url: <%= ENV['DATABASE_URL'] %>

development:
  url: postgres://localhost/project_mosul_development?pool=5

test:
  adapter: postgresql
  database: project_mosul_test
  username: rails_dev
  password: rails_dev