production:
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  sslmode: 'verify-full'
  sslrootcert: 'config/ca/rds.pem'

staging:
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  sslmode: 'verify-full'
  sslrootcert: 'config/ca/rds.pem'

development:
  url: postgres://localhost/project_mosul_development?pool=5

test:
  adapter: postgresql
  database: project_mosul_test
  username: rails_dev
  password: rails_dev
