---
development: &default
  :key: <%= ENV['FLICKR_KEY'] %>
  :secret: <%= ENV['FLICKR_SECRET'] %>

staging:
  <<: *default

production: &defaults
  <<: *default

test:
  :key: "testkey"
  :secret: "testsecret"
